<?xml version="1.0" encoding="utf-8"?>
<report
	progress="">
	<activity
		result="Failed"
		duration="0ms"
		durationms="0"
		type="root"
		rid="2937a63c4a6239df"
		totalerrorcount="0"
		totalwarningcount="0"
		totalsuccesscount="1"
		totalfailedcount="1"
		totalblockedcount="0"
		user="Karun Shrestha"
		host="THINK-PK2N901"
		rxversion="6.2.0.0"
		osversion="Windows 7 Service Pack 1 64bit"
		runtimeversion="4.0.30319.42000"
		procarch="32bit"
		language="en-US"
		screenresolution="3520x1080"
		timestamp="1/30/2017 12:03:15 PM"
		timestampiso="2017-01-30T17:03:15"
		timeoutfactor="1">
		<detail>
			Ranorex Testscript
		</detail>
		<activity
			result="Success"
			duration="1.32s"
			durationms="1321"
			type="test suite"
			rid="12539d7a8aff50"
			totalerrorcount="0"
			totalwarningcount="0"
			totalsuccesscount="1"
			totalfailedcount="1"
			totalblockedcount="0"
			testsuitename="CCHSSmokeTest"
			runconfigname="TestRun"
			runlabel=""
			maxchildren="9">
			<params/>
			<detail>
			</detail>
			<errmsg>
				An internal error occurred while executing the test case. System.Threading.ThreadAbortException: Thread was being aborted.
   at Ranorex.Core.Testing.TestCaseNode.Run(DataContext parentDataContext, Boolean childSkip)
   at Ranorex.Core.Testing.TestCaseNode.RunChildren(IEnumerable`1 entries, TestResult overallResult, Boolean&amp; childSkip, Boolean&amp; tearDownPending)
   at Ranorex.Core.Testing.TestCaseNode.RunChildren(TestResult overallResult, Boolean&amp; childSkip, Boolean tearDownPending)
   at Ranorex.Core.Testing.TestCaseNode.ActuallyRun(Boolean childSkip)
   at Ranorex.Core.Testing.TestCaseNode.Run(DataContext parentDataContext, Boolean childSkip)
			</errmsg>
			<activity
				result="Success"
				duration="1.31s"
				durationms="1314"
				type="test case"
				rid="3398a0a46aaa1b0"
				totalerrorcount="0"
				totalwarningcount="0"
				totalsuccesscount="1"
				totalfailedcount="1"
				totalblockedcount="0"
				testcasename="Master_TC"
				testcaseid="70c0d86a-c505-4b51-be73-845f01aac024"
				datasource="NewConnector2"
				iterationcount="3"
				maxchildren="16">
				<params/>
				<detail>
				</detail>
				<activity
					result="Success"
					duration="1.31s"
					durationms="1311"
					type="test case iteration"
					rid="2426dfdc4ac3b3e6"
					totalerrorcount="0"
					totalwarningcount="0"
					totalsuccesscount="0"
					totalfailedcount="1"
					totalblockedcount="0"
					testcasename="Master_TC"
					iteration="1">
					<datarow>
						<field
							name="BrowserType">
							IE
						</field>
					</datarow>
					<detail>
					</detail>
					<errmsg>
						An internal error occurred while executing the test case. System.Threading.ThreadAbortException: Thread was being aborted.
   at Ranorex.Core.Testing.TestCaseNode.LoadDataFromSource(String dataSourceName, Int32 childCount, TestResult&amp; tr)
   at Ranorex.Core.Testing.TestCaseNode.Run(DataContext parentDataContext, Boolean childSkip)
					</errmsg>
					<activity
						result="Success"
						duration="262ms"
						durationms="262"
						type="test module"
						rid="4aa3ceb8f5dbf5e"
						totalerrorcount="0"
						totalwarningcount="0"
						totalsuccesscount="0"
						totalfailedcount="0"
						totalblockedcount="0"
						modulename="LaunchApplication"
						moduleid="5cd65174-2163-48e5-a8dc-d08bc3999fa5"
						moduletype="Recording">
						<detail>
						</detail>
						<varbindings>
							<varbinding
								name="BrowserType"
								value="IE"/>
						</varbindings>
						<item
							timeRelativeToTestSuiteStartTime="00:00.147"
							timeRelativeToTestModuleStartTime="00:00.001"
							timeWallClock="12:03:15"
							time="00:00.147"
							level="Info"
							category="Data">
							<message>
								Current variable values:<br/>$BrowserType = 'IE'
							</message>
							<metainfo
								loglvl="Info"/>
						</item>
						<item
							timeRelativeToTestSuiteStartTime="00:00.233"
							timeRelativeToTestModuleStartTime="00:00.087"
							timeWallClock="12:03:15"
							time="00:00.233"
							level="Info"
							category="Website">
							<message>
								Opening web site 'https://qa.carecamhealthsystems.com' with browser specified by variable $BrowserType in maximized mode.
							</message>
							<metainfo
								itemindex="0"
								codefile="c:\Users\User\Documents\Ranorex\RanorexStudio Projects\CCHSSmokeTest\CCHSSmokeTest\LaunchApplication.cs"
								codeline="95"
								loglvl="Info"/>
						</item>
					</activity>
					<activity
						result="Failed"
						duration="3ms"
						durationms="3"
						type="test case"
						rid="732616dec9e272b"
						totalerrorcount="0"
						totalwarningcount="0"
						totalsuccesscount="0"
						totalfailedcount="1"
						totalblockedcount="0"
						testcasename="TC1_Change_Password"
						testcaseid="224245c2-f6ee-47d4-908a-70d1ed7ffbdd"
						datasource="ChangePassword"
						iterationcount="0"
						maxchildren="0">
						<params/>
						<errormessage>
							Failed to get rows from data source: Failed to load Excel data. Thread was being aborted.
						</errormessage>
						<detail>
						</detail>
					</activity>
				</activity>
			</activity>
		</activity>
		<item
			timeRelativeToTestSuiteStartTime="00:01.435"
			timeRelativeToTestModuleStartTime="00:01.438"
			timeWallClock="12:03:17"
			time="00:01.435"
			level="Failure"
			category="TestSuite">
			<message>
				Thread was being aborted.
			</message>
			<metainfo
				stacktrace="   at Ranorex.Core.Testing.TestCaseNode.Run(DataContext parentDataContext, Boolean childSkip)
   at Ranorex.Core.Testing.TestSuite.Run(String runConfigName, String runLabel, Dictionary`2 parameters)
   at Ranorex.Core.Testing.TestSuiteRunner.RunInternal(Type containerType, String testSuiteXml, RunParams rp)"
				loglvl="Failure"/>
		</item>
	</activity>
</report>
